[package]
name = "homescript-ls-rs"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/smarthome-go/homescript-ls-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.0", features = ["derive"] }
log = "0.4.17"
loggerv = "0.7.2"
serde = "1.0.163"
smarthome-sdk-rs = "0.10.0"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread", "io-std"] }
toml = "0.7.4"
tower-lsp = "0.19.0"
